#!/usr/bin/env python
# coding: utf-8

# In[6]:


numero_filas=4
numero_columnas=4
matriz = [None] * numero_filas
for i in range(numero_filas):
    matriz[i] = [None] * numero_columnas
print(matriz)


# In[8]:


matriz[0][0]=1
matriz[0][1]=1
matriz[0][2]=1
matriz[0][3]=1
matriz[1][0]=1
matriz[1][1]=1
matriz[1][2]=1
matriz[1][3]=1
matriz[2][0]=1
matriz[2][1]=1
matriz[2][2]=1
matriz[2][3]=1
matriz[3][0]=1
matriz[3][1]=1
matriz[3][2]=1
matriz[3][3]=1
print(matriz)


# In[10]:


import numpy as np #revisar si se tiene instalada la libreria numpy
v4 = np.arange(1, 8) # utilizando la funcion arange de numpy
v4


# In[15]:


# Creando matriz de coeficientes
A = np.array([[1, 2, 3],
              [2, 5, 2],
              [6, -3, 1]])

# Creando matriz de resultados
b = np.array([6, 4, 2])
x = np.linalg.solve(A, b)
print(A)
print(b)
print(x)
A @ x==b


# 
